Repository dataloop-ai/components, pull requests merged in 2023-04, with the labels that each got.

#109 Dl chip fit prop
  .eslintrc.js
  .github/workflows/build-test.yml
  package.json
  src/components/basic/DlChip/DlChip.vue
  src/demo/DlChipDemo.vue
  src/stories/DlChip.stories.js
  tests/DlChip.spec.ts
  tests/DlDateTimeRange/DlCalendar.spec.ts
Labels: enhancement

#110 Hotfix/kpi counter mismatch
  src/components/basic/DlKpi/DlKpi.vue
  src/components/compound/DlCounters/DlCounters.vue
  src/components/compound/DlItem/index.ts
  src/components/essential/DlTypography/DlTypography.vue
  src/demo/DlCounterDemo.vue
  src/stories/DlKpi.stories.js
Labels: bug, enhancement

#116 Fix/dlcl 829 dl-icon svg
  src/components/essential/DlIcon/DlIcon.vue
  src/utils/dynamicSvgImport.ts
Labels: bug

#104 Feat/dlcl 830 dropdown button ellipsis
  src/components/basic/DlEllipsis/DlEllipsis.vue
  src/components/basic/DlEllipsis/index.ts
  src/components/basic/index.ts
  src/components/compound/DlDropdownButton/DlDropdownButton.vue
  src/components/shared/DlItemSection/DlItemSection.vue
  src/demo/DlDropdownButtonDemo.vue
  src/demo/DlEllipsisDemo.vue
  src/demo/index.ts
  src/stories/DlEllipsis.stories.js
  tests/DlDropdownButton.spec.ts
  tests/DlEllipsis.spec.ts
Labels: enhancement

#146 Feat/line chart improvements
  src/components/compound/DlCharts/charts/DlColumnChart/DlColumnChart.vue
  src/components/compound/DlCharts/charts/DlLineChart/DlLineChart.vue
  src/components/compound/DlCharts/types/props.ts
  src/demo/DlLineChartDemo.vue
  src/stories/DlLineChart.stories.js
Labels: bug, enhancement

#147 #114 DlDateTimeRange
  src/components/compound/DlDateTime/DlDateTimeRange/DlDateTimeRange.vue
Labels: bug

#142 Dlcl 844/feat/separator
  src/components/basic/DlSeparator/DlSeparator.vue
  src/components/basic/DlSeparator/index.ts
  src/components/basic/index.ts
  src/demo/DlSeparatorDemo.vue
  src/demo/index.ts
  src/stories/DlSeparator.stories.js
  tests/DlSeparator.spec.ts
Labels: enhancement

#157 156 dlcheckbox add sublabel slot
  src/components/essential/DlCheckbox/DlCheckbox.vue
  src/stories/DlCheckbox.stories.js
Labels: enhancement

#154 DlInput -> show bottom messages on small input components
  src/components/compound/DlInput/DlInput.vue
  src/demo/DlInputDemo.vue
Labels: bug

#163 DlCounters customization
  src/components/basic/DlKpi/DlKpi.vue
  src/components/compound/DlCounters/DlCounters.vue
  src/stories/DlCounters.stories.js
Labels: enhancement

#167 DlAlert -> fix tests
  tests/DlAlert.spec.ts
Labels: bug

#169 DlInput -> rename withoutRootPadding prop to dense
  src/components/compound/DlInput/DlInput.vue
  src/stories/DlInput.stories.js
Labels: enhancement

#170 DlCalendar.spec.ts -> fix calendar tests
  tests/DlDateTimeRange/DlCalendar.spec.ts
Labels: bug

#172 DlTabPanels -> fix render of tabs content
  src/components/compound/DlTabPanels/DlTabPanels.vue
Labels: bug

#175 DlTextarea -> add warning/info/error messages
  src/components/essential/DlTextArea/DlTextArea.vue
  src/demo/DlTextAreaDemo.vue
  src/hooks/use-size-observer.ts
  tests/DlTextArea.spec.ts
Labels: enhancement

#148 feat/DLCL-877-arrow-navigation-in-list
  src/components/basic/DlListItem/DlListItem.vue
  src/components/compound/DlCharts/charts/DlDoughnutChart/DlDoughnutChart.vue
  src/components/compound/DlDropdownButton/DlDropdownButton.vue
  src/components/compound/DlInput/DlInput.vue
  src/components/compound/DlSearches/DlSmartSearch/components/DlSuggestionsDropdown.vue
  src/components/compound/DlSelect/DlSelect.vue
  src/components/essential/DlMenu/DlMenu.vue
  src/demos/DlDropdownButtonDemo.vue
  src/demos/DlMenuDemo.vue
  src/demos/DlSearchDemo.vue
  src/hooks/use-arrow-navigation.ts
  tests/DlDropdownButton.spec.ts
  tests/DlListItem.spec.ts
  tests/DlMenu/DlMenu.spec.ts
  tests/DlSelect/DlSelect.spec.ts
Labels: new

#194 117 dlselect dlmenu position doesnt get updated on scroll
  src/components/essential/DlMenu/DlMenu.vue
  src/hooks/use-tick.ts
  tests/DlMenu/DlMenu.spec.ts
Labels: bug

#200 feat/DLCL-905-dl-list-icon-size
  src/components/basic/DlListItem/DlListItem.vue
  tests/DlListItem.spec.ts
Labels: enhancement, design

#198 fix/DLCL-906-dl-date-time-range-opacity
  src/assets/globals.scss
  src/components/compound/DlDateTime/DlDatePicker/components/DlCalendar.vue
  tests/DlDateTimeRange/DlCalendar.spec.ts
Labels: bug, design

#204 DlChip Changes -
  src/components/basic/DlChip/DlChip.vue
  src/stories/DlChip.stories.js
  tests/DlChip.spec.ts
Labels: bug
