Repository dataloop-ai/components, pull requests merged in 2023-05, with the labels that each got.

#210 DlPagination => fix pagination styles
  src/components/compound/DlPagination/DlPagination.vue
  src/components/compound/DlPagination/components/PageNavigation.vue
  src/components/compound/DlPagination/components/QuickNavigation.vue
Labels: enhancement, design

#251 change card padding
  src/components/basic/DlCard/DlCard.vue
Labels: bug

#254 change close button styles for alert
  src/components/basic/DlAlert/DlAlert.vue
  src/demos/DlAlertDemo.vue
Labels: enhancement, design

#260 258 feature dltoast allow collapsable count
  src/assets/constants.scss
  src/assets/globals.scss
  src/components/compound/DlToast/api/useToast.ts
  src/components/compound/DlToast/components/ToastComponent.vue
  src/components/compound/DlToast/utils/render.ts
  src/demos/DlAlertDemo.vue
  src/demos/DlToastDemo.vue
Labels: enhancement

#264 DlVirtualScroll -> new virtual scroll + markup table
  src/components/basic/DlMarkupTable/DlMarkupTable.vue
  src/components/basic/DlMarkupTable/index.ts
  src/components/basic/index.ts
  src/components/compound/DlTable/DlTable.vue
  src/components/compound/DlTable/styles/dl-table-styles.scss
  src/components/compound/DlTable/utils/getTableMiddle.ts
  src/components/essential/DlList/DlList.vue
  src/components/shared/DlVirtualScroll/DlVirtualScroll.vue
  src/components/shared/DlVirtualScroll/styles/dl-virtual-scroll-styles.scss
  src/components/shared/DlVirtualScroll/useVirtualScroll.ts
  src/demos/DlMarkupTableDemo.vue
  src/demos/DlVirtualScrollDemo.vue
  src/demos/index.ts
  src/stories/DlVirtualScroll.stories.ts
  src/utils/events.ts
  src/utils/render.ts
  tests/DlList.spec.ts
  tests/DlVirtualScroll/DlVirtualScroll.spec.ts
Labels: enhancement

#307 Dl checkbox - issues #216
  src/components/essential/DlCheckbox/DlCheckbox.vue
Labels: bug

#186 DlTabs -> add top-right slot
  misc/._vue2.6-vite
  src/components/compound/DlTabs/DlTabs.vue
  src/components/compound/DlTabs/components/DlTab.vue
  src/components/compound/DlTabs/components/TabsWrapper.vue
  src/demos/DlTabsDemo.vue
  src/demos/DlTooltipDemo.vue
Labels: enhancement

#201 DlButton - added active prop to button
  src/components/basic/DlButton/DlButton.vue
  src/demos/DlButtonDemo.vue
  src/stories/DlButton.stories.js
  src/stories/DlButton.stories.ts
  tests/DlButton.spec.ts
Labels: enhancement, design

#273 DlInput => fix readonly state styles
  src/components/compound/DlInput/DlInput.vue
  src/demos/DlInputDemo.vue
Labels: enhancement, design

#339 [BUG-338] - DlPagination - Removed hardcoded margin & padding.
  src/components/compound/DlPagination/DlPagination.vue
  src/components/compound/DlPagination/components/PaginationLegend.vue
  src/components/compound/DlPagination/components/RowsSelector.vue
Labels: bug
