Repository dataloop-ai/components, pull requests merged in 2023-03, with the labels that each got.

#32 date time picker improvements
  src/assets/globals.scss
  src/components/DlDatePicker/DlCalendar.vue
  src/components/DlDatePicker/DlDatePicker.vue
  tests/DlDateTimeRange/DlCalendar.spec.ts
  tests/DlDateTimeRange/DlDatePicker.spec.ts
Labels: enhancement

#59 StoryBook > documentation reconstruction dlcl-695
  src/demo/DlButtonDemo.vue
  src/stories/DlAlert.stories.js
  src/stories/DlBadge.stories.js
  src/stories/DlButton.stories.js
  src/stories/DlCounters.stories.js
  src/stories/DlDropdownButton.stories.js
  src/stories/DlListItem.stories.js
  src/stories/DlOptionGroup.stories.js
  src/stories/DlPagination.stories.js
  src/stories/DlRange.stories.js
  src/stories/DlSelect.stories.js
  src/stories/DlSlider.stories.js
  src/stories/DlTab.stories.js
  src/stories/DlTextArea.stories.js
  src/stories/DlTextInput.stories.js
  src/stories/DlTooltip.stories.js
  src/stories/DlTypography.stories.js
Labels: enhancement

#62 Docs page
  .github/workflows/build-test.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/docs-deployment.yml
  .github/workflows/npm-publish.yml
  .github/workflows/version-bump.yml
  package-lock.json
Labels: documentation

#61 DLSlider > added padding in input DLCL-759
  src/components/DlSlider/sliderStyles.scss
Labels: bug

#64 DL Counters | add spacing prop
  package-lock.json
  src/components/DlCounters.vue
Labels: enhancement, design

#57 DlPagination > hide selector if only one parameter as page options is given
  src/components/DlPagination/RowsSelector.vue
Labels: design

#65 fix package lock dependencies
  .nvmrc
  .storybook/main.js
  package-lock.json
  package.json
Labels: bug

#60 DlToastMessages > new component development dlcl-710
  src/assets/globals.scss
  src/components/DlAlert.vue
  src/components/DlToastMessage/api/useToast.ts
  src/components/DlToastMessage/components/ToastComponent.vue
  src/components/DlToastMessage/index.ts
  src/components/DlToastMessage/types.ts
  src/components/DlToastMessage/utils/config.ts
  src/components/DlToastMessage/utils/render.ts
  src/demo/DlToastMessageDemo.vue
  src/demo/index.ts
  src/stories/DlToastMessage.stories.js
  tests/DlToastMessage.spec.ts
Labels: new

#63 Fix/dl chips
  src/components/DlChip/DlChip.vue
  src/demo/DlChipDemo.vue
  tests/DlChip.spec.ts
Labels: bug, design

#56 Dl Theme Provider > add analytics color variables
  src/assets/globals.scss
Labels: design

#79 DlTextarea | add textarea keydown emit / fix width
  src/components/DlTextArea.vue
  src/demo/DlTextAreaDemo.vue
Labels: bug, enhancement

#73 Theme Provider | updated colors
  src/assets/globals.scss
Labels: design

#70 DlRadio modelValue props type fixed
  src/components/DlRadio.vue
Labels: bug

#85 #84 - DlCounters-abbreviateNumbers-prop-issue
  src/components/DlCounters.vue
  src/utils/abbreviate-to-string.ts
  tests/utils/abbreviate-to-string.spec.ts
Labels: bug

#89 DlAccordion > issues improvement
  src/components/DlAccordion/AccordionHeader.vue
  src/demo/DlAccordionDemo.vue
Labels: bug

#108 Feat/DLCl-834-DlDialogBoxFooter-buttons
  src/components/compound/DlDialogBox/components/DlDialogBoxFooter.vue
  src/demo/DlDialogBoxDemo.vue
Labels: enhancement

#105 Feat/DLCL-828/DlColorPicker border of the elements
  src/components/essential/DlColorPicker/DlColorPicker.vue
  src/components/essential/DlColorPicker/components/DlColors.vue
  src/demo/DlColorPickerDemo.vue
Labels: enhancement
